import type { CardRarity } from "@okodukai/shared";
import { defineCopy, localized } from "../../i18n";

const plural = (n: number, one: string, many: string) => (n > 1 ? many : one);
const pluralEn = (n: number, one: string, many: string) => (n === 1 ? one : many);

/** Textes de l'ouverture d'un booster (enfant : phrases courtes, jamais de pression). */
export const COPY = localized(
  defineCopy({
    fr: {
      dialogLabel: "Ouverture du booster",
      skip: "Passer",
      soundOn: "Couper le son",
      soundOff: "Remettre le son",
      summonTitle: "Le booster s'éveille",
      summonWaiting: "Tes cartes arrivent…",
      boosterOf: (universe: string) => `Booster ${universe}`,
      crystalPrompt: "Touche le cristal !",
      crystalHold: "Tu peux aussi rester appuyé.",
      crystalLeft: (n: number) => `Encore ${n} ${plural(n, "touche", "touches")}`,
      crystalHint: "Le cristal change de couleur…",
      crystalLabel: (n: number) => `Briser le cristal : encore ${n} ${plural(n, "touche", "touches")}`,
      crystalBreaking: "Le cristal se brise !",
      announce: {
        RARE: "Une carte rare arrive.",
        EPIQUE: "Une carte épique arrive !",
        LEGENDAIRE: "Une carte légendaire se réveille !",
      } as Partial<Record<CardRarity, string>>,
      counter: (i: number, n: number) => `Carte ${i} sur ${n}`,
      flipLabel: "Retourner la carte",
      flipHint: "Touche la carte pour la retourner.",
      flip: "Retourner",
      next: "Carte suivante",
      seeAll: "Voir mes cartes",
      revealAll: "Tout révéler",
      newBadge: "Nouvelle !",
      owned: "Déjà dans ton album",
      summaryTitle: "Ton booster est ouvert",
      summaryNew: (n: number) => `${n} ${plural(n, "nouvelle carte rejoint", "nouvelles cartes rejoignent")} ton album.`,
      summaryNoNew: "Tu avais déjà ces cartes : elles s'ajoutent à tes doubles.",
      openNext: (n: number) => `Booster suivant (${n})`,
      back: "Retour à l'album",
      errorTitle: "Le booster n'a pas pu s'ouvrir.",
      errorBody: "Vérifie ta connexion, puis réessaie. Ton booster t'attend toujours.",
      retry: "Réessayer",
      close: "Fermer",
    },
    en: {
      dialogLabel: "Opening the booster",
      skip: "Skip",
      soundOn: "Mute sound",
      soundOff: "Turn sound back on",
      summonTitle: "The booster wakes up",
      summonWaiting: "Your cards are on their way…",
      boosterOf: (universe: string) => `${universe} booster`,
      crystalPrompt: "Tap the crystal!",
      crystalHold: "You can also press and hold.",
      crystalLeft: (n: number) => `${n} more ${pluralEn(n, "tap", "taps")}`,
      crystalHint: "The crystal is changing colour…",
      crystalLabel: (n: number) => `Break the crystal: ${n} more ${pluralEn(n, "tap", "taps")}`,
      crystalBreaking: "The crystal is breaking!",
      announce: {
        RARE: "A rare card is coming.",
        EPIQUE: "An epic card is coming!",
        LEGENDAIRE: "A legendary card is waking up!",
      },
      counter: (i: number, n: number) => `Card ${i} of ${n}`,
      flipLabel: "Turn the card over",
      flipHint: "Tap the card to turn it over.",
      flip: "Turn over",
      next: "Next card",
      seeAll: "See my cards",
      revealAll: "Reveal all",
      newBadge: "New!",
      owned: "Already in your album",
      summaryTitle: "Your booster is open",
      summaryNew: (n: number) => `${n} new ${pluralEn(n, "card joins", "cards join")} your album.`,
      summaryNoNew: "You already had these cards. They go on your pile of doubles.",
      openNext: (n: number) => `Next booster (${n})`,
      back: "Back to the album",
      errorTitle: "The booster couldn't open.",
      errorBody: "Check your connection, then try again. Your booster is still waiting for you.",
      retry: "Try again",
      close: "Close",
    },
  })
);
