// Textes de la landing publique (français et anglais). Une seule source par section, lue par
// chaque composant avec `useCopy(LANDING)`. Voir docs/LANDING_REDESIGN.md pour l'intention.
import type { CardRarity } from "@okodukai/shared";
import { defineCopy } from "../../i18n";

export const LANDING = defineCopy({
  fr: {
    skip: "Aller au contenu",
    nav: {
      home: "Okodukai, accueil",
      onPage: "Sur cette page",
      how: "Comment ça marche",
      vault: "Le Coffre magique",
      parents: "Pour les parents",
    },
    ctas: {
      known: { primary: "Choisir mon profil", secondary: "Espace parent", nav: "Mon profil" },
      fresh: { primary: "Créer un compte", secondary: "Connexion", nav: "Commencer" },
    },
    hero: {
      title: "Le premier compte",
      titleSoft: "de votre enfant.",
      lead: "Il gagne des pièces virtuelles avec les quêtes que vous lui proposez, puis apprend à les dépenser, les garder ou les placer.",
      how: "Comment ça marche",
      phone: "Démonstration de l'écran d'accueil d'Emma : 32 pièces sur son compte, 70 dans son Coffre magique et une quête à faire.",
      pathLabel: "Son parcours dans Okodukai",
      path: ["Gagner", "Gérer", "Économiser", "Décider", "Comprendre"],
    },
    choice: {
      earn: "Il gagne",
      earnEnd: "10.",
      decide: "À lui de décider",
      decideEm: "quoi en faire.",
      items: [
        { verb: "Dépenser", where: "à la boutique familiale", text: "Un film à choisir, une sortie vélo : vous décidez des récompenses et de leur prix." },
        { verb: "Garder", where: "dans son Coffre magique", text: "Pour s'offrir plus tard quelque chose de plus grand. Chaque lundi, le coffre lui donne une petite prime." },
        { verb: "Placer", where: "dans une partie simulée", text: "Pour voir, relevé après relevé, ce que deviennent ses pièces." },
      ],
      coda: "Dépenser maintenant ou garder pour samedi ?",
      codaStrong: "C'est déjà une décision financière.",
    },
    story: {
      title: "Son premier compte.",
      titleEm: "Sans argent réel.",
      chapters: [
        { title: "La chambre est rangée.", text: "Emma coche sa quête, son père vérifie et valide. Les 10 pièces sont à elle.", screen: "Démonstration : la quête « Ranger sa chambre » validée, 10 pièces gagnées." },
        { title: "Le compte vient de bouger.", text: "Chaque mouvement s'affiche avec sa date et sa raison, comme sur un relevé de banque.", screen: "Démonstration : Mon compte passe à 42 pièces, la nouvelle ligne en haut du relevé." },
        { title: "Elle en met une partie de côté.", text: "20 pièces passent dans son Coffre magique. Chaque lundi, le coffre lui donne une petite prime sur ce qu'elle a gardé.", screen: "Démonstration : 20 pièces vont du compte au Coffre magique, prime de lundi annoncée." },
        { title: "Elle économise pour samedi.", text: "Son objectif, c'est « Glace en famille », une récompense de votre boutique. Il lui manque 10 pièces.", screen: "Démonstration : l'objectif Glace en famille à 90 sur 100." },
        { title: "Elle découvre les placements.", text: "Elle place 20 pièces dans une partie simulée. Chaque soir, un relevé montre ce que le marché en a fait.", screen: "Démonstration : une partie de placement simulée, la courbe et les supports." },
      ],
    },
    quests: {
      title: "Chez Okodukai, l'argent commence par",
      titleEm: "une action.",
      text: "Vous proposez les quêtes : ranger sa chambre, lire, nourrir le chat. Quand il a fini, il vous prévient. Les pièces et l'XP n'arrivent qu'une fois la quête validée par vous.",
      aside: "Toutes les trois quêtes validées rapportent aussi un booster de cartes.",
      sheetsLabel: "Le chemin d'une quête, en démonstration",
      sheets: [
        { title: "Lire 15 minutes", status: "Disponible", note: "Proposée par Sophie" },
        { title: "Vider le lave-vaisselle", status: "En attente du parent", note: "Emma a prévenu : c'est fait" },
        { title: "Ranger sa chambre", status: "Validée", note: "Validée par Papa" },
      ],
      stamp: "Validé",
    },
    vault: {
      title: "Tout dépenser maintenant ?",
      titleEm: "Ou garder pour plus tard ?",
      name: "Coffre magique",
      coins: "pièces",
      goal: "Objectif : Glace en famille",
      captions: [
        "Le coffre est fermé. Tout est encore sur son compte.",
        "Il range 20 pièces. Elles ne partiront pas à la boutique par erreur.",
        "Chaque lundi, le coffre lui donne une petite prime : 1 pièce pour 10 gardées toute la semaine.",
        "Il lui manque 10 pièces pour « Glace en famille ».",
        "Objectif atteint. Samedi, c'est glace en famille.",
      ],
    },
    invest: {
      title: "Que deviennent 100 pièces",
      titleEm: "en dix ans ?",
      text: "Votre enfant place des pièces dans une partie. Chaque soir à 17 h, un relevé montre six mois d'un marché simulé, qui monte et qui baisse. Il apprend à répartir ses pièces et à attendre. À la fin de la partie, le montant revient sur son compte.",
      note: "Le marché est une simulation pédagogique, sans argent réel ni produit financier. Une partie dure dix ans simulés pour les 10-12 ans, cinq pour les 8-9 ans.",
      game: "Ma partie · démonstration",
      coins: "pièces",
      year: (y: number) => `Année ${y} sur 10`,
      chart: "Courbe de démonstration : la valeur monte et descend au fil des dix années, de 100 à 138 pièces.",
      supports: [
        { name: "Sécurisé", move: "bouge très peu" },
        { name: "Prêter", move: "bouge un peu" },
        { name: "Panier Monde", move: "bouge" },
        { name: "Entreprises", move: "bouge beaucoup" },
      ],
    },
    collection: {
      title: "Les bonnes habitudes méritent aussi",
      titleEm: "leurs trésors.",
      text: "Les boosters se gagnent avec les quêtes et ne s'achètent jamais. La collection compte 105 cartes réparties en 14 univers, et c'est vous qui choisissez ceux que votre enfant peut ouvrir.",
      fan: "Sept cartes de la collection, de Commune à Légendaire",
      pack: "Créatures fantastiques",
      cards: ["Dragon", "Marco Polo", "Neptune", "Le feu", "Athéna", "Golem de pierre", "Tokyo"],
    },
    parents: {
      title: "Vous gardez les règles.",
      titleEm: "Il apprend à choisir.",
      controls: [
        { title: "Les quêtes", value: "Vous les créez, vous les validez." },
        { title: "La boutique", value: "Vous choisissez les récompenses et leur prix." },
        { title: "Retraits du Coffre magique", value: "Libres, soumis à votre accord, possibles après une durée ou une fois l'objectif atteint." },
        { title: "Argent de poche", value: "Un montant versé chaque semaine, le jour de votre choix." },
        { title: "Placements", value: "Vous les activez ou non, réglez le rythme des relevés et plafonnez les versements." },
        { title: "Univers de cartes", value: "Vous choisissez ceux qui sont ouverts." },
      ],
      screenAlt: "L'espace parent : les deux enfants, leurs pièces disponibles et au coffre, et une quête à valider.",
      screenCaption: "L'espace parent du foyer de démonstration.",
      foot: "Vous voyez aussi ce qu'il a compris des placements, avec une idée de sujet pour en parler ensemble.",
    },
    trust: {
      title: "Ce qu'Okodukai n'a pas",
      not: ["Pas d'argent réel,", "pas de publicité,", "pas de réseau social,", "pas de chat."],
      yes: "Les pièces sont virtuelles : elles ne s'achètent pas et ne se convertissent pas en euros.",
      yesStrong: "Vous fixez les règles, et les écrans sont pensés pour les 8-12 ans.",
    },
    finale: {
      title: "Sa première aventure",
      titleSoft: "avec l'argent peut commencer ici.",
      text: "Il suffit d'un e-mail et du nom de votre famille, puis d'un profil par enfant. Le reste se règle plus tard.",
      footer: "Okodukai n'est pas une banque. Les pièces sont virtuelles : elles ne s'achètent pas et ne se convertissent pas en euros. Les placements sont une simulation pédagogique.",
    },
    demo: {
      nav: ["Accueil", "Mon trésor", "Quêtes", "Boutique", "Collection"],
      moneyTabs: ["Mon compte", "Coffre magique", "Investir", "Historique"],
      parent: "Parent",
      hello: "Bonjour Emma",
      level: "Niv. 2",
      account: "Mon compte",
      coins: "pièces",
      seeMoney: "Voir mon trésor",
      vault: "Coffre magique",
      vaultGoal: "Glace en famille : il te manque 30 pièces",
      dishwasher: "Vider le lave-vaisselle",
      today: "À faire aujourd'hui",
      questsKicker: "À faire et à gagner",
      questsTitle: "Journal de quêtes",
      room: "Ranger sa chambre",
      approved: "Validée",
      roomDetail: "Lit fait, jouets rangés, bureau dégagé.",
      approvedBy: "Validée par Papa",
      table: "Mettre la table",
      available: "Disponible",
      toast: "+10 pièces",
      toastEnd: "sur ton compte",
      balanceStart: "J'ai",
      week: "Cette semaine :",
      earned: "gagnées",
      spent: "dépensées",
      latest: "Derniers mouvements",
      lines: ["Quête « Ranger sa chambre »", "Récompense « Choisir le dessert »", "Quête « Vider le lave-vaisselle »", "Argent de poche de Sophie"],
      mondayBonus: "Ma prime de lundi",
      bonus: "+7 pièces",
      goals: "Mes objectifs",
      iceCream: "Glace en famille",
      shop: "Boutique",
      of: (a: number, b: number) => `${a} sur ${b}`,
      missing: "Il te manque 10 pièces.",
      book: "Livre au choix",
      next: "Le Coffre magique le remplira ensuite.",
      observatory: "L'observatoire",
      investments: "Mes placements",
      year: "Année 4 sur 10. Prochain relevé ce soir à 17 h.",
      game: "Ma partie",
      placed: "pièces placées : 20",
      simulation: "Simulation",
      safe: "Sécurisé",
      barely: "presque pas bougé",
      companies: "Entreprises",
      more: "▲ 3 de plus",
      world: "Panier Monde",
      less: "▼ 1 de moins",
    },
  },
  en: {
    skip: "Skip to content",
    nav: {
      home: "Okodukai, home",
      onPage: "On this page",
      how: "How it works",
      vault: "The Magic Vault",
      parents: "For parents",
    },
    ctas: {
      known: { primary: "Choose my profile", secondary: "Parent area", nav: "My profile" },
      fresh: { primary: "Create an account", secondary: "Log in", nav: "Get started" },
    },
    hero: {
      title: "Your child's",
      titleSoft: "first account.",
      lead: "Your child earns virtual coins through the quests you set, then learns to spend them, save them or invest them.",
      how: "How it works",
      phone: "Demo of Emma's home screen: 32 coins in her account, 70 in her Magic Vault and one quest to do.",
      pathLabel: "Their path through Okodukai",
      path: ["Earn", "Manage", "Save", "Decide", "Understand"],
    },
    choice: {
      earn: "They earn",
      earnEnd: "10.",
      decide: "It's up to them",
      decideEm: "what happens next.",
      items: [
        { verb: "Spend", where: "at the family shop", text: "Picking the film, a bike ride: you decide the rewards and what they cost." },
        { verb: "Keep", where: "in their Magic Vault", text: "To afford something bigger later. Every Monday, the vault gives them a small bonus." },
        { verb: "Invest", where: "in a simulated game", text: "To see what happens to their coins, one statement after another." },
      ],
      coda: "Spend it now or keep it for Saturday?",
      codaStrong: "That's already a money decision.",
    },
    story: {
      title: "Their first account.",
      titleEm: "No real money.",
      chapters: [
        { title: "The room is tidy.", text: "Emma ticks off her quest, and her dad checks and approves it. The 10 coins are hers.", screen: "Demo: the quest \"Tidy your room\" approved, 10 coins earned." },
        { title: "Her account just changed.", text: "Every movement shows its date and its reason, like a bank statement.", screen: "Demo: My account goes up to 42 coins, with the new line at the top of the statement." },
        { title: "She puts some aside.", text: "20 coins go into her Magic Vault. Every Monday, the vault gives her a small bonus on what she kept.", screen: "Demo: 20 coins move from the account to the Magic Vault, with Monday's bonus shown." },
        { title: "She's saving for Saturday.", text: "Her goal is \"Family ice cream\", a reward from your shop. She needs 10 more coins.", screen: "Demo: the Family ice cream goal at 90 out of 100." },
        { title: "She tries investing.", text: "She puts 20 coins into a simulated game. Every evening, a statement shows what the market did with them.", screen: "Demo: a simulated investment game, with its curve and holdings." },
      ],
    },
    quests: {
      title: "At Okodukai, money starts with",
      titleEm: "doing something.",
      text: "You set the quests: tidy the bedroom, read, feed the cat. When your child is done, they let you know. Coins and XP only arrive once you've approved the quest.",
      aside: "Every third approved quest also gives a booster of cards.",
      sheetsLabel: "A quest from start to finish, as a demo",
      sheets: [
        { title: "Read for 15 minutes", status: "Available", note: "Set by Sophie" },
        { title: "Empty the dishwasher", status: "Waiting for a parent", note: "Emma says it's done" },
        { title: "Tidy your room", status: "Approved", note: "Approved by Dad" },
      ],
      stamp: "Approved",
    },
    vault: {
      title: "Spend it all now?",
      titleEm: "Or keep it for later?",
      name: "Magic Vault",
      coins: "coins",
      goal: "Goal: Family ice cream",
      captions: [
        "The vault is shut. Everything is still in the account.",
        "20 coins go in. They won't get spent at the shop by accident.",
        "Every Monday, the vault gives a small bonus: 1 coin for every 10 kept all week.",
        "Only 10 coins to go for \"Family ice cream\".",
        "Goal reached. Saturday is ice cream with the family.",
      ],
    },
    invest: {
      title: "What happens to 100 coins",
      titleEm: "over ten years?",
      text: "Your child puts coins into a game. Every evening at 5 pm, a statement shows six months of a simulated market that goes up and down. They learn to split their coins and to wait. When the game ends, the amount goes back into their account.",
      note: "The market is a teaching simulation, with no real money and no financial product. A game lasts ten simulated years for 10 to 12 year olds, and five for 8 to 9 year olds.",
      game: "My game · demo",
      coins: "coins",
      year: (y: number) => `Year ${y} of 10`,
      chart: "Demo curve: the value rises and falls over the ten years, from 100 to 138 coins.",
      supports: [
        { name: "Safe", move: "barely moves" },
        { name: "Lending", move: "moves a little" },
        { name: "World basket", move: "moves" },
        { name: "Companies", move: "moves a lot" },
      ],
    },
    collection: {
      title: "Good habits deserve",
      titleEm: "their treasures too.",
      text: "Boosters are earned through quests and can never be bought. The collection has 105 cards across 14 worlds, and you choose which ones your child can open.",
      fan: "Seven cards from the collection, from Common to Legendary",
      pack: "Fantastic creatures",
      cards: ["Dragon", "Marco Polo", "Neptune", "Fire", "Athena", "Stone golem", "Tokyo"],
    },
    parents: {
      title: "You set the rules.",
      titleEm: "They learn to choose.",
      controls: [
        { title: "Quests", value: "You create them and you approve them." },
        { title: "The shop", value: "You choose the rewards and their prices." },
        { title: "Magic Vault withdrawals", value: "Free, with your approval, after a set time or once the goal is reached." },
        { title: "Pocket money", value: "A set amount every week, on the day you choose." },
        { title: "Investing", value: "Switch it on or off, choose how often statements arrive and cap the deposits." },
        { title: "Card worlds", value: "You choose which ones are open." },
      ],
      screenAlt: "The parent area: both children, their coins available and in the vault, and a quest to approve.",
      screenCaption: "The parent area of the demo family.",
      foot: "You can also see what your child has understood about investing, with an idea for talking it over together.",
    },
    trust: {
      title: "What Okodukai doesn't have",
      not: ["No real money,", "no ads,", "no social network,", "no chat."],
      yes: "Coins are virtual: they can't be bought and can't be turned into real money.",
      yesStrong: "You set the rules, and the screens are made for 8 to 12 year olds.",
    },
    finale: {
      title: "Their first adventure",
      titleSoft: "with money can start here.",
      text: "All it takes is an email address and your family name, then one profile per child. The rest can wait.",
      footer: "Okodukai is not a bank. Coins are virtual: they can't be bought or turned into real money. Investing is a teaching simulation.",
    },
    demo: {
      nav: ["Home", "My treasure", "Quests", "Shop", "Collection"],
      moneyTabs: ["My account", "Magic Vault", "Invest", "History"],
      parent: "Parent",
      hello: "Hi Emma",
      level: "Lvl. 2",
      account: "My account",
      coins: "coins",
      seeMoney: "See my treasure",
      vault: "Magic Vault",
      vaultGoal: "Family ice cream: 30 coins to go",
      dishwasher: "Empty the dishwasher",
      today: "To do today",
      questsKicker: "To do and to earn",
      questsTitle: "Quest log",
      room: "Tidy your room",
      approved: "Approved",
      roomDetail: "Bed made, toys away, desk clear.",
      approvedBy: "Approved by Dad",
      table: "Set the table",
      available: "Available",
      toast: "+10 coins",
      toastEnd: "in your account",
      balanceStart: "I have",
      week: "This week:",
      earned: "earned",
      spent: "spent",
      latest: "Latest movements",
      lines: ["Quest \"Tidy your room\"", "Reward \"Choose dessert\"", "Quest \"Empty the dishwasher\"", "Pocket money from Sophie"],
      mondayBonus: "My Monday bonus",
      bonus: "+7 coins",
      goals: "My goals",
      iceCream: "Family ice cream",
      shop: "Shop",
      of: (a: number, b: number) => `${a} of ${b}`,
      missing: "You need 10 more coins.",
      book: "Book of my choice",
      next: "The Magic Vault will fill it next.",
      observatory: "The observatory",
      investments: "My investments",
      year: "Year 4 of 10. Next statement tonight at 5 pm.",
      game: "My game",
      placed: "coins invested: 20",
      simulation: "Simulation",
      safe: "Safe",
      barely: "barely moved",
      companies: "Companies",
      more: "▲ 3 more",
      world: "World basket",
      less: "▼ 1 less",
    },
  },
});

/** Raretés des cartes de l'éventail (dans l'ordre de `collection.cards`). */
export const FAN_RARITIES: CardRarity[] = ["COMMUNE", "PEU_COMMUNE", "RARE", "LEGENDAIRE", "EPIQUE", "RARE", "PEU_COMMUNE"];
